# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MRZScannerObjC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRZScannerObjC
pod 'DynamsoftCameraEnhancer','3.0.1'
pod 'DynamsoftLabelRecognizer','2.2.20'
pod 'DynamsoftCore', '2.0.2'

end
